<?php

declare(strict_types=1);

namespace KWIO\GutenbergBlocks;

/**
 * Enqueues assets from the configured dist directory.
 */
class AssetCollector
{
    /**
     * Holds the configurated options.
     *
     * @var PluginConfigDTO
     */
    private PluginConfigDTO $pluginConfig;

    /**
     * @param PluginConfigDTO $pluginConfig The configurated options.
     */
    public function __construct(PluginConfigDTO $pluginConfig)
    {
        $this->pluginConfig = $pluginConfig;
    }

    /**
     * Enqueues blocks.css and critical.css files in admin and frontend (nonblocking).
     * @see Loader::int
     */
    public function enqueueAssets(): void
    {
        wp_enqueue_style(
            $this->pluginConfig->prefix . '-blocks',
            $this->pluginConfig->dirUrl . $this->pluginConfig->distDir . 'blocks.css',
            [],
            $this->shortenVersionHash($this->getVersionHash('blocks.css')),
            is_admin() ? 'all' : 'nonblocking'
        );

        if (!empty($this->getCriticalCss())) {
            wp_add_inline_style($this->pluginConfig->prefix . '-blocks', $this->getCriticalCss());
        }
    }

    /**
     * Enqueues additional editor styles and block registration script.
     * @see Loader::int
     */
    public function enqueueEditorAssets(): void
    {
        $handle = $this->pluginConfig->prefix . '-blocks-editor';
        $manifest = $this->getAssetManifest('editor');
        $domain = preg_replace('/-theme$/', '', $this->pluginConfig->prefix);

        wp_enqueue_script(
            $handle,
            $this->pluginConfig->dirUrl . $this->pluginConfig->distDir . 'editor.js',
            $manifest['dependencies'],
            $this->shortenVersionHash($manifest['version']),
            true
        );

        wp_set_script_translations(
            $handle,
            $domain,
            $this->pluginConfig->translationsPath
        );
    }

    /**
     * Enqueues JavaScript file for frontend and sets a global variable to access the WP-REST-API root URL.
     * @see Loader::int
     */
    public function enqueueScripts(): void
    {
        $manifest = $this->getAssetManifest('blocks');

        wp_enqueue_script(
            $this->pluginConfig->prefix . '-blocks',
            $this->pluginConfig->dirUrl . $this->pluginConfig->distDir . 'blocks.js',
            $manifest['dependencies'],
            $this->shortenVersionHash($manifest['version']),
            true
        );
    }

    /**
     * Loads the asset manifest generated by `@wordpress/dependency-extraction-webpack-plugin`.
     *
     * @param string $entry webpack entry name.
     *
     * @return array Information of the current entry.
     */
    private function getAssetManifest(string $entry): array
    {
        $manifestPath = $this->pluginConfig->dirPath . $this->pluginConfig->distDir . "{$entry}.asset.php";
        if (!file_exists($manifestPath)) {
            return [
                'dependencies' => [],
                'version' => $this->getVersionHash($entry . '.js')
            ];
        }

        return require $manifestPath;
    }

    /**
     * Extracts and inlines styles from critical.css file.
     *
     * @return string Extracte styles.
     */
    private function getCriticalCss(): string
    {
        $criticalCssPath = $this->pluginConfig->dirPath . $this->pluginConfig->distDir . 'critical.css';
        if (!is_readable($criticalCssPath)) {
            return '';
        }

        $criticalCss = file_get_contents($criticalCssPath);
        $criticalCss = str_replace('../../../../', content_url('/'), $criticalCss);

        return trim($criticalCss);
    }

    /**
     * Returns hash of last changed timestamp.
     *
     * @param string $asset Asset name.
     *
     * @return string Hashed timestamp.
     */
    private function getVersionHash(string $asset): string
    {
        $assetPath = $this->pluginConfig->dirPath . $this->pluginConfig->distDir . $asset;
        if (!is_readable($assetPath)) {
            return '';
        }

        return md5((string)filemtime($assetPath));
    }

    /**
     * Trims hashed timestamp.
     *
     * @param string $hash Hashed timestamp.
     *
     * @return string Trimmed hash.
     */
    private function shortenVersionHash(string $hash): string
    {
        return substr($hash, 0, 12);
    }
}