name: Docs
on:
  push:
      branches-ignore:
        - develop
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: phpDocumentor generate
        run: docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d ./src -t ./docs/reference --template=.phpdoc/templates
      - name: commit generated phpdocs
        run: |
          git add . -f
          git diff-index --quiet HEAD || git commit -m "update phpdoc" && git push