name: Tests
on:
  push:
      branches-ignore:
        - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text